routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'IndexController@index')->name('index');
Route::get('/detail', 'PostController@show1');
Route::resource('/post', 'PostController');
Route::resource('/thread', 'ThreadController');
Route::resource('/comment', 'CommentController', ['only' => ['update', 'destroy']]);
Route::post('/comment/create/{thread}', 'CommentController@addThreadComment')->name('threadcomment.store');
Route::post('/reply/create/{comment}', 'CommentController@addReplyComment')->name('replycomment.store');
Route::post('/thread/mark-as-solution', 'ThreadController@markAsSolution')->name('markAsSolution');
Route::post('/comment/like', 'LikeController@toggleLike')->name('toggleLike');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

resources/views/partials/css-plug.blade.php
<link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="{{ asset('css/bootswatch.css') }}">
<link rel="stylesheet" href="{{ asset('css/style.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{{ asset('vendor/slick/slick.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('vendor/slick/slick-theme.css') }}">

resources/views/partials/footer.blade.php
<footer>
    <div class="container">
        <div class="text-center">
            Copyright © 2018 <a href="{{ route('index') }}">CekSehatku</a> • <a href="#"><i class="fa fa-facebook"></i></a> • <a href=""><i class="fa fa-twitter"></i></a>
        </div>
    </div>
</footer>

resources/views/partials/js-plug.blade.php
<script src="{{ asset('vendor/slick/slick.js') }}" type="text/javascript" charset="utf-8"></script>

resources/views/partials/navbar-login.blade.php
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary nav-pad-1">
    <div class="container">
        <a class="navbar-brand" href="{{ route('thread.index') }}"><b><i class="fa fa-heartbeat"></i> CekSehatku Forum</b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav ml-auto">
                @guest
                    <li class="nav-item"><a class="nav-link" href="{{ route('login') }}"><i class="fa fa-user-circle"></i> MASUK</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ route('register') }}"><i class="fa fa-hand-o-right"></i> DAFTAR</a></li>
                @else
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Pertanyaan Saya <span class="badge badge-light">0</span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Pertanyaan anda sudah dijawab oleh Dr. Hendra</a>
                            <a class="dropdown-item" href="#">Pertanyaan anda sudah dijawab oleh Dr. Novia</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ Auth::user()->name }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Profil</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                                Keluar
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
            {{-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Ketik disini ...">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Cari</button>
            </form> --}}
        </div>
    </div>
</nav>

resources/views/partials/navbar.blade.php
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary nav-pad-1">
    <div class="container">
        <a class="navbar-brand" href="{{ route('thread.index') }}"><b><i class="fa fa-heartbeat"></i> CekSehatku Forum</b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav ml-auto">
                {{-- <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li> --}}
                {{-- <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form> --}}
                @guest
                    <li class="nav-item"><a class="nav-link" href="{{ route('login') }}"><i class="fa fa-user-circle"></i> MASUK</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ route('register') }}"><i class="fa fa-hand-o-right"></i> DAFTAR</a></li>
                @else
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Pertanyaan Saya <span class="badge badge-light">0</span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Pertanyaan anda sudah dijawab oleh Dr. Hendra</a>
                            <a class="dropdown-item" href="#">Pertanyaan anda sudah dijawab oleh Dr. Novia</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ Auth::user()->name }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Profil</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                                Keluar
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
            {{-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Ketik disini ...">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Cari</button>
            </form> --}}
        </div>
    </div>
</nav>