routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'IndexController@index')->name('index');
Route::get('/detail', 'PostController@show1');
Route::resource('/post', 'PostController');
Route::resource('/thread', 'ThreadController');
Route::resource('/comment', 'CommentController', ['only' => ['update', 'destroy']]);
Route::post('/comment/create/{thread}', 'CommentController@addThreadComment')->name('threadcomment.store');
Route::post('/reply/create/{comment}', 'CommentController@addReplyComment')->name('replycomment.store');
Route::post('/thread/mark-as-solution', 'ThreadController@markAsSolution')->name('markAsSolution');
Route::post('/comment/like', 'LikeController@toggleLike')->name('toggleLike');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = "posts";

    protected $fillable = [
        'title', 'user_id', 'slug', 'short_description',
        'description', 'image', 'published',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }


}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use File;
use Auth;
use App\Post;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request);
        try {
            $user_id = Auth::user()->id;
            $title = $request->title;
            /** Validasi agar slug tidak sama */
            $slug = str_slug($title, '-');
            if (Post::where('slug', $slug)->first() != null)
                $slug = $slug . '-' . time();
            $short_description = $request->short_description;
            $description = $request->description;
            $published = true;

            $save_image = null;
            /** Insert Image */
            if ($request->hasFile('image')) {
                $save_image = $this->saveImage($title, $request->file('image'));
            }
            $image = $filename;

            $post = Post::create([
                'user_id' => $user_id,
                'title' => $title,
                'slug' => $slug,
                'short_description' => $short_description,
                'description' => $description,
                'image' => $image,
                'published' => $published
            ]);

            return redirect()->route('admin.post')
                ->with('msg-success', 'Post Created Success');
        } catch (\Exception $e) {
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);
        return view('posts.show');
    }

    public function show1() {
        return view('posts.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        try {
            $post = Post::where('slug', $slug)->first();
            return view('posts.edit', compact('post'));
        } catch (\Exception $e) {
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $post = Post::findOrFail($id);

            $user_id = Auth::user()->id;
            $title = $request->title;
            /** Validasi agar slug tidak sama */
            $slug = str_slug($title, '-');
            if (Post::where('slug', $slug)->first() != null)
                $slug = $slug . '-' . time();
            $short_description = $request->short_description;
            $description = $request->description;
            $published = true;

            $save_image = null;
            /** Insert Image */
            if ($request->hasFile('image')) {
                $save_image = $this->saveImage($title, $request->file('image'));
            }
            $image = $filename;
        } catch (\Exception $e) {
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $post = Post::findOrFail($id);
            if (!empty($post->image))
                File::delete(public_path('images/posts/' . $post->image));
            $post->delete();

            return redirect()->route('product.index')->with($alert);
        } catch (\Exception $e) {
            return redirect()->back()
                ->with(['error' => $e->getMessage()]);
        }
    }

    private function saveImage($name, $photo)
    {
        /** Buat nama file */
        $image_name = $name . uniqid() . '.' . $photo->getClientOriginalExtension();

        /** Buat tempat penyimpanan gambar */
        $path = public_path('images/posts');

        /** Cek sudah ada directory */
        if (!File::isDirectory($path)) {
            File::makeDirectory($path, 0777, true, true);
        }

        /** Simpan gambar */
        Image::make($photo)->save($path . '/' . $image_name);

        return $image_name;
    }

}

resources/views/posts/create.blade.php
@extends('layouts.main')
@section('title', 'Buat Post')

@section('top-resource')
<style>
.sejenis {
    width: 100px;
}
</style>
@endsection

@section('content')
    <div class="container" style="margin-top:7rem;">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-header">
                        Baca Artikel
                    </div>
                    <div class="card-body" style="padding: 0px;">
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" 
                                        class="sejenis" alt="Manfaat Aroma Terapi">
                                    </div>
                                    <div class="col-md-8">
                                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" 
                                        class="sejenis" alt="Manfaat Aroma Terapi">
                                    </div>
                                    <div class="col-md-8">
                                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" 
                                        class="sejenis" alt="Manfaat Aroma Terapi">
                                    </div>
                                    <div class="col-md-8">
                                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" 
                                        class="sejenis" alt="Manfaat Aroma Terapi">
                                    </div>
                                    <div class="col-md-8">
                                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" 
                                        class="sejenis" alt="Manfaat Aroma Terapi">
                                    </div>
                                    <div class="col-md-8">
                                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-header">
                        BUAT POST
                    </div>
                    <div class="card-body">
                        <form action="{{ route('post.store') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="title">Judul</label>
                                <input type="text" class="form-control" name="title" 
                                placeholder="{{ old('title') }}" style="border: 1px solid #ecf0f1">
                            </div>

                            <div class="form-group">
                                <label for="short_description">Deskripsi Singkat</label>
                                <textarea class="form-control" name="short_description" id="short_description" 
                                cols="30" rows="3" style="border: 1px solid #ecf0f1">{{ old('short_description') }}</textarea>
                            </div>

                            <div class="form-group">
                                <label for="description">Deskripsi</label>
                                <textarea class="form-control my-editor" id="description" name="description" 
                                cols="30" rows="10" style="border: 1px solid #ecf0f1">{!! old('description') !!}</textarea>
                                {{-- <script src="{{ asset('vendor/tinymce_4.8.0/tinymce/js/tinymce/tinymce.min.js') }}"></script> --}}
                            </div>

                            <div class="form-group">
                                <label for="image" class="col-md-4 control-label">Gambar</label>
                                {{-- <img width="820" height="481" /> --}}
                                <input type="file" class="uploads form-control" style="margin-top: 20px; border: 1px solid #ecf0f1" 
                                name="image" value="{{ old('image') }}">
                            </div>

                            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Buat</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('bottom-resource')

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.main')
@section('title', 'Edit Post')

@section('top-resource')
@endsection

@section('content')
    <div class="container" style="margin-top:7rem;">
        <div class="row">
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Laravel
                        <span class="badge badge-primary badge-pill">14</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Blade
                        <span class="badge badge-primary badge-pill">2</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Cache
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Database
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Lumen
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                </ul>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-header">
                        EDIT POST
                    </div>
                    <div class="card-body">
                        <form action="{{ route('post.store') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="title">Judul</label>
                                <input type="text" class="form-control" name="title" 
                                value="{{ $product->title }}" style="border: 1px solid #ecf0f1">
                            </div>

                            <div class="form-group">
                                <label for="short_description">Deskripsi Singkat</label>
                                <textarea class="form-control" name="short_description" id="short_description" 
                                cols="30" rows="3" style="border: 1px solid #ecf0f1" value="{{ $product->short_description }}"></textarea>
                            </div>

                            <div class="form-group">
                                <label for="description">Deskripsi</label>
                                <textarea class="form-control my-editor" id="description" name="description" 
                                cols="30" rows="10" style="border: 1px solid #ecf0f1" value="description">{!! old('description') !!}</textarea>
                                {{-- <script src="{{ asset('vendor/tinymce_4.8.0/tinymce/js/tinymce/tinymce.min.js') }}"></script> --}}
                            </div>

                            <div class="form-group">
                                <label for="image" class="col-md-4 control-label">Gambar</label>
                                <input type="file" class="uploads form-control" style="margin-top: 20px; border: 1px solid #ecf0f1" 
                                name="image" value="{{ old('image') }}">
                            </div>

                            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Simpan Perubahan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('bottom-resource')

@endsection

resources/views/posts/index.blade.php
@extends('layouts.main')
@section('title', 'Semua Post')

@section('top-resource')
<style>
</style>
@endsection

@section('content')
<div class="container post" style="margin-top:7rem;">
    <h1 class="article">Artikel Kesehatan</h1>
    <hr class="style-eight">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="card mb-3">
                <div class="card-header">
                    <div class="title">
                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                    </div>
                </div>
                <div class="card-body">
                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                    <div class="author">
                        Ditulis oleh: <a href="#" title="penulis">Dr. Hendra</a>
                    </div>
                    <div class="description">
                        <p>Aromaterapi adalah cara memanfaatkan minyak alami yang diekstrak dari tumbuhan dengan tujuan meningkatkan kesehatan secara fisik maupun psikis.</p>
                        <a href="#">Lebih Lanjut <i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="card mb-3">
                <div class="card-header">
                    <div class="title">
                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                    </div>
                </div>
                <div class="card-body">
                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                    <div class="author">
                        Ditulis oleh: <a href="#" title="penulis">Dr. Hendra</a>
                    </div>
                    <div class="description">
                        <p>Aromaterapi adalah cara memanfaatkan minyak alami yang diekstrak dari tumbuhan dengan tujuan meningkatkan kesehatan secara fisik maupun psikis.</p>
                        <a href="#">Lebih Lanjut <i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="card mb-3">
                <div class="card-header">
                    <div class="title">
                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                    </div>
                </div>
                <div class="card-body">
                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                    <div class="author">
                        Ditulis oleh: <a href="#" title="penulis">Dr. Hendra</a>
                    </div>
                    <div class="description">
                        <p>Aromaterapi adalah cara memanfaatkan minyak alami yang diekstrak dari tumbuhan dengan tujuan meningkatkan kesehatan secara fisik maupun psikis.</p>
                        <a href="#">Lebih Lanjut <i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="card mb-3">
                <div class="card-header">
                    <div class="title">
                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                    </div>
                </div>
                <div class="card-body">
                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                    <div class="author">
                        Ditulis oleh: <a href="#" title="penulis">Dr. Hendra</a>
                    </div>
                    <div class="description">
                        <p>Aromaterapi adalah cara memanfaatkan minyak alami yang diekstrak dari tumbuhan dengan tujuan meningkatkan kesehatan secara fisik maupun psikis.</p>
                        <a href="#">Lebih Lanjut <i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="card mb-3">
                <div class="card-header">
                    <div class="title">
                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                    </div>
                </div>
                <div class="card-body">
                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                    <div class="author">
                        Ditulis oleh: <a href="#" title="penulis">Dr. Hendra</a>
                    </div>
                    <div class="description">
                        <p>Aromaterapi adalah cara memanfaatkan minyak alami yang diekstrak dari tumbuhan dengan tujuan meningkatkan kesehatan secara fisik maupun psikis.</p>
                        <a href="#">Lebih Lanjut <i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="card mb-3">
                <div class="card-header">
                    <div class="title">
                        <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                    </div>
                </div>
                <div class="card-body">
                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                    <div class="author">
                        Ditulis oleh: <a href="#" title="penulis">Dr. Hendra</a>
                    </div>
                    <div class="description">
                        <p>Aromaterapi adalah cara memanfaatkan minyak alami yang diekstrak dari tumbuhan dengan tujuan meningkatkan kesehatan secara fisik maupun psikis.</p>
                        <a href="#">Lebih Lanjut <i class="fa fa-angle-double-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#">Sebelum</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Selanjutnya</a></li>
        </ul>
    </nav>
</div>
@endsection

@section('bottom-resource')

@endsection

resources/views/posts/show.blade.php
@extends('layouts.main')
@section('title', 'Rincian Post')

@section('top-resource')
<style>
</style>
@endsection

@section('content')
<div class="container detail-post" style="margin-top: 7rem;">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-8">
            <div class="card mb-3">
                <div class="card-header">
                    <div class="title">
                        <h1>Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</h1>
                    </div>
                </div>
                <div class="card-body">
                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                    <div class="author">
                        Ditulis oleh: <a href="#" title="penulis">Dr. Hendra 28 Oktober 2018</a>
                    </div>
                    <div class="description">
                        <p>Saat ini, aromaterapi banyak digunakan sebagai perawatan alternatif untuk berbagai kondisi kesehatan. Mulai dari stres, masalah pencernaan, insomnia, depresi, dan lain-lain. Tak heran kalau semakin lama semakin mudah buat Anda untuk menemukan berbagai produk aromaterapi yang katanya berkhasiat bagi tubuh. Apakah benar ada banyak manfaat aromaterapi buat Anda? Cari tahu jawabannya di bawah ini.</p>
                        <p>Sebenarnya, apa yang dimaksud dengan aromaterapi?
                            Aromaterapi adalah cara memanfaatkan minyak alami yang diekstrak dari tumbuhan dengan tujuan meningkatkan kesehatan secara fisik maupun psikis. Minyak yang digunakan adalah minyak esensial yang terbuat dari berbagai tanaman obat, bunga, herbal, akar, buah, dan pepohonan yang tumbuh di seluruh dunia. Menurut sejumlah penelitian, beberapa jenis minyak esensial sudah terbukti memiliki efek positif untuk meningkatkan kondisi fisik dan emosional seseorang.
                            Sudah lebih dari 5000 tahun, aromaterapi dipercaya diantara berbagai budaya di seluruh dunia. Dipercaya bahwa aromaterapi merupakan penyembuh alami yang dapat berfungsi sebagai anti bakteri, antiradanga, sekaligus memberikan efek antinyeri.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4">
            <div class="card mb-3">
                <div class="card-header subscribe">
                    Berlangganan Artikel
                    {{-- <p>Masukkan email untuk berlangganan</p> --}}
                    <form action="">
                        <input type="text" class="form-control" placeholder="Masukkan email untuk berlangganan">
                        <button class="btn btn-primary">Kirim <i class="fa fa-send"></i></button>
                    </form>
                </div>
            </div>

            <div class="card mb-3">
                <div class="card-header">
                    Artikel Sejenis
                </div>
                <div class="card-body" style="padding: 0px;">
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                                </div>
                                <div class="col-md-8">
                                    <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                                </div>
                                <div class="col-md-8">
                                    <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                                </div>
                                <div class="col-md-8">
                                    <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                                </div>
                                <div class="col-md-8">
                                    <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="{{ asset('images/posts/manfaat-aromaterapi.jpg') }}" alt="Manfaat Aroma Terapi">
                                </div>
                                <div class="col-md-8">
                                    <a href="#">Apa Saja Manfaat Aromaterapi Bagi Kesehatan Tubuh?</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection

@section('bottom-resource')

@endsection