routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'IndexController@index')->name('index');
Route::get('/detail', 'PostController@show1');
Route::resource('/post', 'PostController');
Route::resource('/thread', 'ThreadController');
Route::resource('/comment', 'CommentController', ['only' => ['update', 'destroy']]);
Route::post('/comment/create/{thread}', 'CommentController@addThreadComment')->name('threadcomment.store');
Route::post('/reply/create/{comment}', 'CommentController@addReplyComment')->name('replycomment.store');
Route::post('/thread/mark-as-solution', 'ThreadController@markAsSolution')->name('markAsSolution');
Route::post('/comment/like', 'LikeController@toggleLike')->name('toggleLike');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use CommentableTrait;

    protected $guarded = [];

    protected $fillable = [
        'subject', 'thread', 'type', 'user_id'
    ];

    /**
     * sebuah thread dimiliki oleh seorang user
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * [MOVE] ke CommentableTrait
     */
    // public function comments()
    // {
    //     return $this->morphMany('App\Comment', 'commentable')->latest();
    // }
}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Thread;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class ThreadController extends Controller
{
    /**
     * Create a new controller instance.
     * Untuk setiap controller yang harus terautentikasi gunakan function contsruct
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function markAsSolution()
    {
        // dd(Input::all());

        /**
         * Setiap Thread punya 1 buah solution,
         * dimana ketika jawaban sudah ditandai sebagai solution,
         * maka kolom solution pada table thread akan diisi dengan comment_id
         * yang menjadi solusi pada thread tersebut.
         */
        $threadId = Input::get('threadId');
        $solutionId = Input::get('solutionId');

        $thread = Thread::findOrFail($threadId);

        // melakukan update pada table thread
        $thread->solution = $solutionId;

        if ($thread->save()) {
            if (request()->ajax()) {
                return response()->json(['status' => 'success', 'message' => 'marked as solution']);
            }

            return back()->with('msg-success', 'Solution Marked');
        }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $threads = Thread::paginate(15);

        // $id = auth()->user()->id; ambil id yang login
        // $id = Auth::user()->id;

        return view('threads.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'subject' => 'required',
            'thread' => 'required',
            'type' => 'required',
        ]);

        Thread::create([
            'subject' => $request->subject,
            'thread' => $request->thread,
            'type' => $request->type,
            'user_id' => Auth::user()->id,
        ]);

        return redirect()->route('thread.index')->with('msg-success', 'Thread Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $thread = Thread::findOrFail($id);

        return view('threads.detail', compact('thread'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $thread = Thread::findOrFail($id);

        return view('threads.edit', compact('thread'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $thread = Thread::findOrFail($id);

        if(Auth::user()->id != $thread->user_id) {
            return abort(401, 'Unathorized');
        }

        $thread->update([
            'subject' => $request->subject,
            'thread' => $request->thread,
            'type' => $request->type,
        ]);

        return redirect()->route('thread.index')->with('msg-success', 'Thread Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $thread = Thread::findOrFail($id);

        if(Auth::user()->id != $thread->user_id) {
            return abort(401, 'Unathorized');
        }

        $thread->delete();

        return redirect()->route('thread.index')->with('msg-delete', 'Thread Deleted');
    }
}

resources/views/threads/create.blade.php
@extends('layouts.main')
@section('title', 'Create Thread')

@section('top-resource')
<style>
</style>
@endsection

@section('content')
    <div class="container" style="margin-top:7rem;">
        <div class="row">
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Laravel
                        <span class="badge badge-primary badge-pill">14</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Blade
                        <span class="badge badge-primary badge-pill">2</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Cache
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Database
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Lumen
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                </ul>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-header">
                        CREATE THREAD
                    </div>
                    <div class="card-body">
                        <form action="{{ route('thread.store') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="subject">Subject</label>
                                <input type="text" class="form-control" name="subject" placeholder="Enter subject" placeholder="{{ old('subject') }}" style="border: 1px solid #ecf0f1">
                            </div>
                            <div class="form-group">
                                <label for="type">Type</label>
                                <input type="text" class="form-control" name="type" placeholder="Enter type" placeholder="{{ old('type') }}" style="border: 1px solid #ecf0f1">
                            </div>
                            <div class="form-group">
                                <label for="thread">Thread</label>
                                <textarea class="form-control" name="thread" placeholder="Enter thread" cols="30" rows="10" style="border: 1px solid #ecf0f1">{{ old('thread') }}</textarea>
                            </div>
                            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Create</button>
                        </form>
                    </div>
                </div>
                {{-- <div class="jumbotron">
                    <h4>Create Thread</h4><br>
                    <form action="{{ route('thread.store') }}" method="POST">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="subject">Subject</label>
                            <input type="text" class="form-control" name="subject" placeholder="Enter subject" placeholder="{{ old('subject') }}">
                        </div>
                        <div class="form-group">
                            <label for="type">Type</label>
                            <input type="text" class="form-control" name="type" placeholder="Enter type" placeholder="{{ old('type') }}">
                        </div>
                        <div class="form-group">
                            <label for="thread">Thread</label>
                            <textarea class="form-control" name="thread" placeholder="Enter thread" cols="30" rows="10">{{ old('thread') }}</textarea>
                        </div>
                        

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div> --}}
            </div>
        </div>
    </div>
@endsection

@section('bottom-resource')

@endsection

resources/views/threads/detail.blade.php
@extends('layouts.main')
@section('title', 'Detail')

@section('top-resource')
<style>
.card-inner{
    margin-left: 4rem;
}
</style>
@endsection

@section('content')
<div class="container" style="margin-top:7rem;">
    <div class="row forum">
        <div class="col-sm-3 col-md-3 col-lg-3">
            <div class="profile-user-info">
                <a href="https://laravel.io/user/nervous-energy">
                    <img class="img-circle" src="https://www.gravatar.com/avatar/09827822f952b6b0e2bbbbe182618d3f?s=25&amp;d=https%3A%2F%2Flaravel.io%2Favatar%2Fsidney%2520machara">
                </a>
                <h2 class="profile-user-name">{{ $thread->user->name }}</h2>
                <div class="profile-social-icons">
                    <a href="#">
                        <i class="fa fa-github"></i>
                    </a>
                </div>
                <hr>
                <a class="btn btn-primary btn-block" href="https://laravel.io/forum/typeerror-cannot-read-property-channel-of-undefined/subscribe">
                    Subscribe
                </a>
                <a class="btn btn-link btn-block" href="http://laravel-forum.pro/thread">
                    <i class="fa fa-arrow-left"></i> Back
                </a>
            </div>
        </div>
        <div class="col-sm-9 col-md-9 col-lg-9">
            {{-- <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Thread</a></li>
                <li class="breadcrumb-item active">{{ $thread->subject }}</li>
            </ol> --}}
            @if(session('msg-success'))
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fa fa-check"></i> Success!</h5>
                    {{ session('msg-success') }}
                </div>
            @endif
            @if(session('msg-delete'))
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fa fa-ban"></i> Alert!</h5>
                    {{ session('msg-delete') }}
                </div>
            @endif

            <h1>"{{ $thread->subject }}"</h1>
            <hr>

            <div class="card mb-3">
                <div class="card-header">
                    <div class="profile">
                        <a href="https://laravel.io/user/sidney%20machara">
                            <img class="rounded-circle img-fluid" style="width:2rem;" src="https://www.gravatar.com/avatar/09827822f952b6b0e2bbbbe182618d3f?s=25&amp;d=https%3A%2F%2Flaravel.io%2Favatar%2Fsidney%2520machara">
                        </a>
                        <a href="https://laravel.io/user/sidney%20machara">{{ $thread->user->name }}</a>
                        posted 1 month ago

                        <a href="https://laravel.io/forum/tags/laravel">
                            <span class="badge badge-default pull-right">{{ $thread->type }}</span>
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    {{-- <h4 class="card-title">Primary card title</h4>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> --}}
                    <h4>{{ $thread->subject }}</h4>
                    <h5>{{ $thread->thread }}</h5>
                    <br>
                    @if(Auth::user()->id == $thread->user_id)
                        <a class="btn btn-primary" href="{{ route('thread.edit', $thread->id) }}"><i class="fa fa-edit"></i> Edit</a>
                        <form action="{{ route('thread.destroy', $thread->id) }}" method="POST" style="display:inline;">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button class="btn btn-danger" type="submit"><i class="fa fa-close"></i> Delete</button>
                        </form>
                    @endif
                </div>
            </div>
            @include('threads.comment')
            <div class="alert alert-info">
                <p>
                    Please make sure you've read our
                    <a href="https://laravel.io/rules" class="alert-link">Forum Rules</a> before replying to this thread.
                </p>
            </div>

            <div class="card mb-3">
                {{-- <div class="card-header">
                    <h4 class="text-center">Comment Here:</h4>
                </div> --}}
                <div class="card-body">
                    @if(count($errors) > 0)
                        <div class="alert alert-warning alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <h5><i class="icon fa fa-warning"></i> Alert!</h5>
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @if(session('error'))
                        <div class="alert alert-warning alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <h5><i class="icon fa fa-warning"></i> Alert!</h5>
                            {{ session('error') }}
                        </div>
                    @endif
                    <form action="{{ route('threadcomment.store', $thread->id) }}" method="POST">
                        {{ csrf_field() }}
                        <textarea class="form-control" name="body" id="body" cols="30" rows="10" placeholder="Write for comment . . . . .">{{ old('comment') }}</textarea>
                        <button type="submit" class="btn btn-primary btn-block" style="margin-top:1rem;"><i class="fa fa-check"></i> Comment</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



@endsection

@section('bottom-resource')
<script>
    /**
     * Ketika user klik reply maka textarea untuk reply muncul,
     * jika user klik lagi reply dengan textarea yang sedang aktif,
     * maka textarea akan nonaktif lagi
     */
    function toggleReply(commentId) {
        $('.reply-form-' + commentId).toggleClass('d-none');
    }

    /**
     * Ajax untuk mark up solution
     */
    function markAsSolution(threadId, solutionId, elem) {
        var csrf_token = '{{ csrf_token() }}';
        $.post('{{ route('markAsSolution') }}', {threadId:threadId, solutionId:solutionId, _token:csrf_token}, function(data) {
            $(elem).text('Solution');
        });
    }

    function likeIt(commentId, elem) {
        var csrf_token = '{{ csrf_token() }}';
        $.post('{{ route('toggleLike') }}', {commentId:commentId, _token:csrf_token}, function(data) {
            console.log(data);
        });
    }
</script>
@endsection

resources/views/threads/edit.blade.php
@extends('layouts.main')
@section('title', 'Edit Thread')

@section('top-resource')
@endsection

@section('content')
    <div class="container" style="margin-top:8rem;">
        <div class="row">
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Cras justo odio
                        <span class="badge badge-primary badge-pill">14</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Dapibus ac facilisis in
                        <span class="badge badge-primary badge-pill">2</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Morbi leo risus
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                </ul>
            </div>
            <div class="col-md-8">
                <div class="jumbotron">
                    <h4>Edit Thread</h4><br>
                    <form action="{{ route('thread.update', $thread->id) }}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="subject">Subject</label>
                            <input type="text" class="form-control" name="subject" value="{{ $thread->subject ? $thread->subject : old('subject') }}" placeholder="{{ old('subject') }}">
                        </div>

                        <div class="form-group">
                            <label for="type">Type</label>
                            <input type="text" class="form-control" name="type" value="{{ $thread->type ? $thread->type : old('type') }}" placeholder="{{ old('type') }}">
                        </div>

                        <div class="form-group">
                            <label for="thread">Thread</label>
                            <textarea class="form-control" name="thread" placeholder="{{ old('thread') }}" cols="30" rows="10">{{ $thread->thread ? $thread->thread : old('thread') }}</textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('bottom-resource')

@endsection

resources/views/threads/index.blade.php
@extends('layouts.main')
@section('title', 'Home')

@section('top-resource')
@endsection

@section('content')
    <div class="container" style="margin-top:7rem;">
        <h1>Forum</h1>
        <hr>
        <div class="row">
            <div class="col-sm-3 col-md-3 col-lg-3">
                <a class="btn btn-primary btn-block mb-3" href="{{ route('thread.create') }}">Create Thread</a>
                {{-- <form class="">
                    <input class="form-control" type="text" placeholder="Enter keyword . . . ." style="border: 1px solid black;">
                    <button class="btn btn-secondary mt-2" type="submit">Search</button>
                </form> --}}
                <hr>
                <h4>Tags</h4>
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Laravel
                        <span class="badge badge-primary badge-pill">14</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Blade
                        <span class="badge badge-primary badge-pill">2</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Cache
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Database
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Lumen
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                </ul>
            </div>
            <div class="col-sm-9 col-md-9 col-lg-9">
                @if(session('msg-success'))
                    <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <h5><i class="icon fa fa-check"></i> Success!</h5>
                            {{ session('msg-success') }}
                    </div>
                @endif
                @if(session('msg-delete'))
                    <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <h5><i class="icon fa fa-ban"></i> Alert!</h5>
                            {{ session('msg-delete') }}
                    </div>
                @endif

                @forelse($threads as $thread)
                    <div class="card mb-3">
                        <div class="card-header">
                            <div class="profile">
                                <a href="https://laravel.io/user/sidney%20machara">
                                    <img class="rounded-circle img-fluid" style="width:2rem;" src="https://www.gravatar.com/avatar/09827822f952b6b0e2bbbbe182618d3f?s=25&amp;d=https%3A%2F%2Flaravel.io%2Favatar%2Fsidney%2520machara">
                                </a>
                                <a href="https://laravel.io/user/sidney%20machara">{{ $thread->user->name }}</a>
                                {{ $thread->updated_at }}

                                <a href="https://laravel.io/forum/tags/laravel">
                                    <span class="badge badge-default pull-right">{{ $thread->type }}</span>
                                </a>
                            </div>
                        </div>
                        <div class="card-body">
                            <a href="{{ route('thread.show', $thread->id) }}">{{ $thread->subject }}</a>
                        </div>
                    </div>
                @empty
                    No Thread
                @endforelse
            </div>
        </div>

    </div>
@endsection

@section('bottom-resource')

@endsection